# Stage 1: Build the React application
FROM node:20.18.1-alpine3.19 AS build

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn

# Copy the rest of the application code
COPY . .

# Expose port 80 for the container (Azure handles serving)
EXPOSE 80
CMD ["echo", "Static files ready for Azure."]