version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Map port 8080 on the host to 8080 in the container
    restart: unless-stopped
