FROM node:20.18.1-alpine3.19

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn

# Copy the rest of the application code
COPY . .

# Expose the dev server port (Vite default is 5173)
EXPOSE 80

# Start the development server
CMD ["yarn", "dev", "--host"]