services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bionicscolar-backend-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    environment:
      - ENVIRONMENT=development

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bionicscolar-frontend-dev
    ports:
      - '3000:3000' # Map Vite's dev server port
    volumes:
      - ./frontend:/app # Mount the current directory for live development
      - /app/node_modules # Persist node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev --host

  # backend-prod:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.prod
  #   container_name: bionicscolar-backend-prod
  #   command: daphne -b 0.0.0.0 -p 8000 api.asgi:application
  #   volumes:
  #     - static_volume:/app/staticfiles/
  #     - media_volume:/app/mediafiles/
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./backend/.env.prod
  #   environment:
  #     - ENVIRONMENT=production

  # frontend-prod:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   container_name: bionicscolar-frontend-prod
  #   ports:
  #     - '8080:80' # Map port 8080 to NGINX
  #   environment:
  #     - NODE_ENV=production

# volumes:
#   static_volume:
#   media_volume: